name: Sample GitHub Actions
on:
  workflow_dispatch:
    inputs:
       client_payload:
          description: The Client payload
          required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Update check
        if: always()
        run: |
          CHECK_ID=$(curl -X POST https://centralci.eu.ngrok.io/check --data '{"installation_id": ${{ fromJSON(github.event.inputs.client_payload).installation_id }}, "owner": "${{ fromJSON(github.event.inputs.client_payload).owner }}", "repo": "${{ fromJSON(github.event.inputs.client_payload).repo }}", "head_sha": "${{ fromJSON(github.event.inputs.client_payload).head_sha }}", "check_name": "Linter" }')
          echo "CHECK_RUN_ID=$CHECK_ID" >> $GITHUB_ENV
      - name: Checkout original repository
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(github.event.inputs.client_payload).full_repo_path }}
          ref: ${{ fromJSON(github.event.inputs.client_payload).head_sha }}
          fetch-depth: 0
          token: ${{ fromJSON(github.event.inputs.client_payload).github_token }}
          path: "code/"
      - name: lint
        uses: rahul-deepsource/pyaction@1.4.0
      - if: failure()
        run: echo "RESULT=failure" >> $GITHUB_ENV
      - if: success()
        run: echo "RESULT=success" >> $GITHUB_ENV
      - name: Update failed check
        if: always()
        run: |
          curl -X PUT https://centralci.eu.ngrok.io/check/$CHECK_RUN_ID --data '{"installation_id": ${{ fromJSON(github.event.inputs.client_payload).installation_id }}, "owner": "${{ fromJSON(github.event.inputs.client_payload).owner }}", "repo": "${{ fromJSON(github.event.inputs.client_payload).repo }}", "head_sha": "${{ fromJSON(github.event.inputs.client_payload).head_sha }}", "conclusion": '$RESULT', "check_name": "Linter" }'
